name: Deploy Customer1 Prod Infra

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Pulumi CLI
        uses: pulumi/actions@v3
        with:
          pulumi-version: latest

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.CUSTOMER1_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CUSTOMER1_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy Pulumi Stack
        run: |
          pulumi login s3://customer1-prod-pulumi-bucket
          pulumi stack select organization/project1/prod
          cd customers/customer1/project1/prod
          pulumi up --yes
